// Shape of the precomputed dataset consumed by the app.
//
// This dataset is generated by scripts/build-dataset.ts from OpenDota's public
// API and shipped as a compact JSON so the client never has to hit OpenDota's
// rate-limited endpoints at runtime.

export type Bracket =
  | 'herald'
  | 'guardian'
  | 'crusader'
  | 'archon'
  | 'legend'
  | 'ancient'
  | 'divine'
  | 'immortal';

export const BRACKETS: Bracket[] = [
  'herald',
  'guardian',
  'crusader',
  'archon',
  'legend',
  'ancient',
  'divine',
  'immortal',
];

export type PrimaryAttr = 'str' | 'agi' | 'int' | 'all';
export type AttackType = 'Melee' | 'Ranged';

export interface Hero {
  /** OpenDota hero id, e.g. 1 = Anti-Mage. */
  id: number;
  /** Internal name, e.g. "npc_dota_hero_antimage". */
  name: string;
  /** Display name, e.g. "Anti-Mage". */
  localizedName: string;
  primaryAttr: PrimaryAttr;
  attackType: AttackType;
  /** OpenDota role tags, e.g. ["Carry", "Escape", "Nuker"]. */
  roles: string[];
  /** Absolute URL to the wide hero image. */
  img: string;
  /** Absolute URL to the square hero icon. */
  icon: string;
}

export interface BracketRecord {
  /** Number of games the hero was picked in this bracket. */
  pick: number;
  /** Number of those games that were won. */
  win: number;
}

export interface HeroStat {
  heroId: number;
  byBracket: Partial<Record<Bracket, BracketRecord>>;
  proPick: number;
  proWin: number;
  proBan: number;
}

/** How a hero performs against a single other hero (adversarial matchup). */
export interface Matchup {
  /** The opposing hero id. */
  heroId: number;
  gamesPlayed: number;
  wins: number;
}

export interface ItemCount {
  itemId: number;
  /** Item key, e.g. "power_treads". */
  key: string;
  count: number;
}

export interface HeroItemBuckets {
  start: ItemCount[];
  early: ItemCount[];
  mid: ItemCount[];
  late: ItemCount[];
}

export interface ItemConstant {
  id: number;
  key: string;
  localizedName: string;
  img?: string;
}

/**
 * Attribute seed derived in the pipeline from OpenDota ability data. Damage
 * types are real (from each ability's dmg_type); the tactical flags are a
 * best-effort heuristic (keyword scan of ability text) meant to be overridden
 * by the curated overlay in heroAttributes.ts.
 */
export interface HeroAttributeSeed {
  damageTypes?: ('magical' | 'physical' | 'pure')[];
  hardDisable?: boolean;
  initiation?: boolean;
  teamfight?: boolean;
  waveclear?: boolean;
  sustain?: boolean;
  save?: boolean;
  escape?: boolean;
  powerSpike?: 'early' | 'mid' | 'late';
  durable?: boolean;
}

export interface Dataset {
  /** Game patch the data was aggregated on, e.g. "7.37". */
  patch: string;
  /** ISO timestamp of when the dataset was generated. */
  generatedAt: string;
  heroes: Hero[];
  stats: HeroStat[];
  /** heroId -> list of matchups vs every other hero. */
  matchups: Record<number, Matchup[]>;
  /** heroId -> popular items split into game phases. */
  itemPopularity: Record<number, HeroItemBuckets>;
  /** itemId -> item metadata for rendering builds. */
  itemConstants: Record<number, ItemConstant>;
  /** heroId -> attribute seed derived from ability data (optional). */
  heroAttributes?: Record<number, HeroAttributeSeed>;
}
