// Calibrated predictor weights. Regenerated by scripts/calibrate.ts from real
// pro-match outcomes; falls back to the committed pre-calibration defaults.

import raw from '../../assets/weights.json';

export interface ModelWeights {
  intercept: number;
  matchup: number;
  meta: number;
  composition: number;
  timing: number;
  calibratedAt: string | null;
  samples: number;
}

export const modelWeights = raw as ModelWeights;

/** True once the weights have been fit against real matches. */
export const isCalibrated = (modelWeights.samples ?? 0) > 0;
